-- ============================================================
-- CAM×AI SUITE — Shared PostgreSQL Schema
-- All 5 workflows share this database
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── CLIENTS
-- One record per person Cameron is searching for
CREATE TABLE clients (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name            VARCHAR(255) NOT NULL,
  email           VARCHAR(255) NOT NULL UNIQUE,
  phone           VARCHAR(30),
  company         VARCHAR(255),
  notes           TEXT,
  -- Search preferences
  property_type   VARCHAR(50),        -- 'retail', 'office', 'industrial', 'mixed'
  min_sqft        INTEGER,
  max_sqft        INTEGER,
  max_monthly     NUMERIC(10,2),
  transaction_type VARCHAR(20),       -- 'lease' or 'sale'
  max_sale_price  NUMERIC(12,2),
  search_frequency VARCHAR(20) DEFAULT 'daily',  -- 'daily', 'weekly', 'monthly'
  -- Map bounds (optional)
  geo_bounds      JSONB,              -- { north, south, east, west }
  -- Status
  active          BOOLEAN DEFAULT true,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── PROPERTIES
-- Master property table — populated from CoStar, Crexi, LoopNet APIs
CREATE TABLE properties (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  external_id     VARCHAR(255),        -- ID from source platform
  source          VARCHAR(50),         -- 'costar', 'crexi', 'loopnet', 'mls', 'parcel_db'
  address         VARCHAR(500) NOT NULL,
  city            VARCHAR(100) DEFAULT 'Tucson',
  state           VARCHAR(10) DEFAULT 'AZ',
  zip             VARCHAR(20),
  lat             NUMERIC(10,7),
  lng             NUMERIC(10,7),
  property_type   VARCHAR(50),
  sqft            INTEGER,
  lot_size_acres  NUMERIC(8,3),
  year_built      INTEGER,
  asking_monthly  NUMERIC(10,2),
  asking_sale     NUMERIC(12,2),
  available_date  DATE,
  listing_status  VARCHAR(50),         -- 'available', 'proposed', 'under_construction'
  is_listed       BOOLEAN DEFAULT true,
  sprinklered     BOOLEAN,
  parking_ratio   NUMERIC(5,2),
  traffic_count   INTEGER,
  cross_street    VARCHAR(255),
  photos          JSONB,               -- Array of photo URLs
  raw_data        JSONB,               -- Full API response stored for reference
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(external_id, source)
);

-- ── CLIENT SEARCHES
-- Snapshot of search results per client per day (for diffing)
CREATE TABLE client_searches (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id       UUID REFERENCES clients(id) ON DELETE CASCADE,
  searched_at     TIMESTAMPTZ DEFAULT NOW(),
  property_ids    UUID[],              -- Array of property IDs returned
  new_property_ids UUID[],            -- Properties not in previous search
  total_count     INTEGER,
  email_sent      BOOLEAN DEFAULT false,
  sms_sent        BOOLEAN DEFAULT false,
  email_sent_at   TIMESTAMPTZ,
  sms_sent_at     TIMESTAMPTZ
);

-- ── REPORTS
-- Generated PDF reports
CREATE TABLE reports (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id       UUID REFERENCES clients(id),
  title           VARCHAR(500),
  parameters      JSONB,               -- Search params used
  property_ids    UUID[],
  pdf_url         VARCHAR(1000),       -- Path or cloud URL
  generated_at    TIMESTAMPTZ DEFAULT NOW(),
  sent_at         TIMESTAMPTZ
);

-- ── OWNERS
-- Property owner records built from skip trace pipeline
CREATE TABLE owners (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  property_id     UUID REFERENCES properties(id),
  llc_name        VARCHAR(500),
  parcel_number   VARCHAR(100),
  -- Principals found
  principals      JSONB,               -- [{name, role, email, phone, linkedin}]
  -- Source data
  pima_data       JSONB,               -- Raw Pima County GIS data
  az_corp_data    JSONB,               -- Raw AZ Corp Commission data
  attom_data      JSONB,               -- Raw ATTOM data
  -- Confidence
  confidence_score INTEGER,            -- 0-100
  trace_status    VARCHAR(50) DEFAULT 'pending',  -- 'pending', 'found', 'failed'
  traced_at       TIMESTAMPTZ,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── LEADS
-- Leads generated by outreach engine (WF3)
CREATE TABLE leads (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  listing_id      UUID REFERENCES properties(id),
  -- Lead info
  name            VARCHAR(255),
  company         VARCHAR(255),
  email           VARCHAR(255),
  phone           VARCHAR(30),
  linkedin_url    VARCHAR(500),
  -- Lease history that made them a match
  lease_address   VARCHAR(500),
  lease_sqft      INTEGER,
  lease_date      DATE,
  lease_source    VARCHAR(100),        -- 're_daily_news', 'crexi', 'costar'
  -- Scoring
  match_score     VARCHAR(20),         -- 'hot', 'warm', 'cold'
  match_reason    TEXT,
  -- Campaign
  email_draft     TEXT,
  email_sent      BOOLEAN DEFAULT false,
  email_sent_at   TIMESTAMPTZ,
  response_status VARCHAR(50),         -- 'interested', 'not_interested', 'no_response', 'follow_up'
  responded_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── CAMPAIGNS
-- Email campaigns (WF3)
CREATE TABLE campaigns (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  listing_id      UUID REFERENCES properties(id),
  name            VARCHAR(255),
  status          VARCHAR(50) DEFAULT 'draft',  -- 'draft', 'sending', 'sent', 'complete'
  lead_count      INTEGER DEFAULT 0,
  sent_count      INTEGER DEFAULT 0,
  response_count  INTEGER DEFAULT 0,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  launched_at     TIMESTAMPTZ
);

-- ── ACTIVITY LOG
-- Audit trail for everything
CREATE TABLE activity_log (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workflow        VARCHAR(50),         -- 'wf1', 'wf2', etc.
  action          VARCHAR(100),
  entity_type     VARCHAR(50),
  entity_id       UUID,
  details         JSONB,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── INDEXES
CREATE INDEX idx_properties_source ON properties(source);
CREATE INDEX idx_properties_type ON properties(property_type);
CREATE INDEX idx_properties_listed ON properties(is_listed);
CREATE INDEX idx_client_searches_client ON client_searches(client_id);
CREATE INDEX idx_client_searches_date ON client_searches(searched_at);
CREATE INDEX idx_leads_listing ON leads(listing_id);
CREATE INDEX idx_leads_status ON leads(response_status);
CREATE INDEX idx_owners_property ON owners(property_id);
CREATE INDEX idx_owners_status ON owners(trace_status);
