import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import campaignRoutes from './routes/campaigns';
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.get('/health', (_req, res) => res.json({ status: 'ok', workflow: 'outreach-engine', timestamp: new Date().toISOString() }));
app.use('/api/campaigns', campaignRoutes);
const PORT = process.env.PORT || 3003;
app.listen(PORT, () => console.log(`[WF3] Outreach Engine running on port ${PORT}`));
export default app;
